# Generated by Django 5.0.14 on 2026-07-21 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_role_can_override_gates'),
        ('procurement', '0004_purchaseorder_classification_purchaseorder_po_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-disables this policy for new pinnings only; never affects packages already pinned.')),
                ('is_canonical_default', models.BooleanField(default=False, help_text='Sole determinant of the canonical default policy family (Charter Section 3.3). Settable only where organization IS NULL.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='NULL means platform-scoped. NULL is a necessary precondition for is_canonical_default but never itself the marker of canonical status.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_policies', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'gate policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GatePolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('gate_schema', models.JSONField(blank=True, default=dict, help_text='Exactly six top-level keys, A1-A6 (Charter Section 3.1/3.2). Immutable once published.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='procurement_gates.gatepolicy')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_versions', to='procurement_gates.gatepolicyversion')),
            ],
            options={
                'ordering': ['policy', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='PackagePolicyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pinned_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('gate_progression_exempt', models.BooleanField(default=False)),
                ('exemption_reason', models.TextField(blank=True, default='')),
                ('exemption_granted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exemption_granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_assignments', to='procurement.procurementpackage')),
                ('pinned_by', models.ForeignKey(blank=True, help_text='NULL for system-assigned pins (e.g. the existing-package migration) -- never disguised as a real approver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_assignments', to='procurement_gates.gatepolicyversion')),
            ],
            options={
                'ordering': ['-pinned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='gatepolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_gate_policy_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='gatepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_canonical_default', True)), fields=('is_canonical_default',), name='unique_canonical_gate_policy'),
        ),
        migrations.AddConstraint(
            model_name='gatepolicyversion',
            constraint=models.UniqueConstraint(fields=('policy', 'version_number'), name='unique_gate_policy_version_number'),
        ),
        migrations.AddConstraint(
            model_name='packagepolicyassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('package',), name='unique_active_package_policy_assignment'),
        ),
    ]
