# Generated by Django 5.0.14 on 2026-07-19 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_number',
            field=models.CharField(blank=True, help_text='The physical building\'s own number on the site plan, e.g. "11", "12".', max_length=20),
        ),
        migrations.AddField(
            model_name='floor',
            name='label',
            field=models.CharField(blank=True, help_text='Verbatim floor label when it is not a single integer, e.g. "4-5" for a combined penthouse floor.', max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='apartment_letter',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='apartment_number',
            field=models.CharField(blank=True, help_text='Source "Apt. Number" value, e.g. "A1", "417".', max_length=30),
        ),
        migrations.AddField(
            model_name='unit',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='bedrooms_label',
            field=models.CharField(blank=True, help_text='Source "Bedrooms" value verbatim — kept as text since some rows say "Estudio"/"Studio", not a number.', max_length=30),
        ),
        migrations.AddField(
            model_name='unit',
            name='has_service_room',
            field=models.BooleanField(blank=True, help_text='Null when not stated by the source.', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='internal_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_penthouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='permanent_code',
            field=models.CharField(blank=True, help_text='Stable identifier generated once at creation (apps.projects.services.build_permanent_code) and never regenerated automatically — it must survive every later reassignment.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='source_row_reference',
            field=models.CharField(blank=True, help_text='Provenance: source document + row identifier this unit was imported from.', max_length=255),
        ),
        migrations.AddField(
            model_name='unit',
            name='terrace_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='total_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='floor',
            name='level',
            field=models.IntegerField(blank=True, help_text='Numeric sort key; a combined floor label (e.g. "4-5") uses its first level here.', null=True),
        ),
        migrations.CreateModel(
            name='BuildingFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(help_text='Canonical display name, e.g. "ARENA T1", "SOLE PH".', max_length=100)),
                ('code', models.SlugField(help_text='Used in the permanent unit code, e.g. "arena-t1".')),
                ('source_label', models.CharField(blank=True, help_text='Verbatim label as it appears in the source document (provenance), e.g. "SOLE A", "SOLE B".', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('uses_building_segment', models.BooleanField(default=True, help_text='Whether the permanent unit code includes a building segment. False for hotel-style buildings with already-unique sequential room numbers (e.g. PALMERA).')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_families', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'building families',
                'ordering': ['display_name'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.AddField(
            model_name='building',
            name='family',
            field=models.ForeignKey(blank=True, help_text='Nullable for backward compatibility with pre-existing Building rows created before this grouping layer existed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='projects.buildingfamily'),
        ),
    ]
