# Generated by Django 5.0.14 on 2026-07-19 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_role_can_override_gates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(help_text='E.g. "exporter_of_record", "visibility_mode".', max_length=100)),
                ('frozen_current_value', models.TextField(blank=True)),
                ('proposed_new_value', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('affected_relationships', models.TextField(blank=True)),
                ('risk_impact', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('withdrawn', 'Retirado')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DerivedArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('source_version', models.CharField(blank=True, max_length=100)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('source_classification', models.CharField(choices=[('china_internal', 'Interno China'), ('source_private', 'Privado de origen (fábrica)'), ('trading_company_confidential', 'Confidencial de la comercializadora'), ('supplier_shared', 'Compartido con proveedor'), ('client_project', 'Proyecto de cliente'), ('client_shared', 'Compartido con cliente'), ('operational_shared', 'Compartido operativo'), ('restricted_finance', 'Financiero restringido'), ('legal_required', 'Requerido legalmente')], max_length=40)),
                ('authorized_source_projection', models.JSONField(default=dict, help_text='The exact field set actually sent to the transformation step — never the full source.')),
                ('artifact_type', models.CharField(choices=[('translation', 'Traducción'), ('summary', 'Resumen'), ('analysis', 'Análisis'), ('redaction', 'Redacción/versión sanitizada'), ('client_safe_document', 'Documento seguro para cliente'), ('report', 'Reporte')], max_length=30)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('author_or_model', models.CharField(help_text='E.g. a username, or "mock-translate-v1".', max_length=150)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('policy_version', models.CharField(default='1', max_length=20)),
                ('classification', models.CharField(choices=[('china_internal', 'Interno China'), ('source_private', 'Privado de origen (fábrica)'), ('trading_company_confidential', 'Confidencial de la comercializadora'), ('supplier_shared', 'Compartido con proveedor'), ('client_project', 'Proyecto de cliente'), ('client_shared', 'Compartido con cliente'), ('operational_shared', 'Compartido operativo'), ('restricted_finance', 'Financiero restringido'), ('legal_required', 'Requerido legalmente')], max_length=40)),
                ('body_text', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('draft', 'Borrador'), ('reviewed', 'Revisado'), ('approved', 'Aprobado')], default='draft', max_length=20)),
                ('is_stale', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DisclosureGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_scope', models.JSONField(default=list, help_text='List of permitted field codes, e.g. ["manufacturer_name"].')),
                ('classification_before', models.CharField(choices=[('china_internal', 'Interno China'), ('source_private', 'Privado de origen (fábrica)'), ('trading_company_confidential', 'Confidencial de la comercializadora'), ('supplier_shared', 'Compartido con proveedor'), ('client_project', 'Proyecto de cliente'), ('client_shared', 'Compartido con cliente'), ('operational_shared', 'Compartido operativo'), ('restricted_finance', 'Financiero restringido'), ('legal_required', 'Requerido legalmente')], max_length=40)),
                ('permitted_projection', models.JSONField(blank=True, default=dict, help_text='Frozen client-safe projection actually released.')),
                ('reason', models.TextField()),
                ('effective_from', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('organization', 'Organización'), ('individual', 'Individuo'), ('site', 'Sitio operativo')], default='organization', max_length=20)),
                ('display_name', models.CharField(help_text='Internal working name — never assumed client-safe by itself.', max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('is_hidden_by_default', models.BooleanField(default=False, help_text='True for upstream sources (factories, contacts) that must never be client-visible without an explicit Disclosure Grant, regardless of visibility mode.')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'parties',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PartyMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('standard', 'Estándar'), ('controlled_opaque', 'Opaco controlado'), ('high_risk', 'Alto riesgo')], default='standard', max_length=20)),
                ('indicator_codes', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_code', models.SlugField(help_text='Free-text role code — new roles never require a schema change.', max_length=60)),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('suspended', 'Suspendido'), ('ended', 'Finalizado')], default='active', max_length=20)),
                ('client_visible', models.BooleanField(default=False, help_text="Whether this Party's participation in this role is itself visible to client-side users.")),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability_code', models.CharField(max_length=60)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
