# Generated by Django 5.0.14 on 2026-07-19 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_role_can_override_gates'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('governance', '0001_initial'),
        ('procurement', '0004_purchaseorder_classification_purchaseorder_po_kind_and_more'),
        ('projects', '0002_building_building_number_floor_label_and_more'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilitygrant',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capability_grants', to='procurement.procurementpackage'),
        ),
        migrations.AddField(
            model_name='capabilitygrant',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Set when granted directly to a user rather than via a role assignment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capability_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='procurement.procurementpackage'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='derivedartifact',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='derivedartifact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='derivedartifact',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='derivedartifact',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='governance.derivedartifact'),
        ),
        migrations.AddField(
            model_name='disclosuregrant',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disclosuregrant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disclosuregrant',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosure_grants', to='procurement.procurementpackage'),
        ),
        migrations.AddField(
            model_name='disclosuregrant',
            name='recipient_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='disclosuregrant',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disclosuregrant',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='hosting_organization',
            field=models.ForeignKey(help_text="The tenant this Party record lives under for isolation purposes — the organization administering the relationship, not necessarily the Party's own legal owner.", on_delete=django.db.models.deletion.CASCADE, related_name='hosted_parties', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='party',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Set when this Party is itself a tenant organization (e.g. the buyer).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='party',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Set when this Party wraps an existing vendor/factory Supplier record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='disclosuregrant',
            name='recipient_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='governance.party'),
        ),
        migrations.AddField(
            model_name='disclosuregrant',
            name='source_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosure_grants', to='governance.party'),
        ),
        migrations.AddField(
            model_name='partymembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partymembership',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='governance.party'),
        ),
        migrations.AddField(
            model_name='partymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskflag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskflag',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='procurement.procurementpackage'),
        ),
        migrations.AddField(
            model_name='riskflag',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='organization_context',
            field=models.ForeignKey(help_text='The hosting/administering organization this assignment is scoped under.', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='procurement.procurementpackage'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='governance.party'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shipments.shipment'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='governance.roleassignment'),
        ),
        migrations.AddField(
            model_name='capabilitygrant',
            name='role_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capability_grants', to='governance.roleassignment'),
        ),
        migrations.AddIndex(
            model_name='derivedartifact',
            index=models.Index(fields=['content_type', 'object_id'], name='governance__content_41987f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partymembership',
            unique_together={('party', 'user')},
        ),
    ]
