# Generated by Django 5.0.14 on 2026-07-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_override_gates',
            field=models.BooleanField(default=False, help_text="Grants permission to override a blocked workflow gate with a written reason (spec: 'any authorized override must require a permission'). Never granted by default — assigned explicitly per role in seed data (e.g. Dirección, Gerencia)."),
        ),
    ]
