# Generated by Django 5.0.14 on 2026-07-18 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('customs', '0002_initial'),
        ('documents', '0001_initial'),
        ('procurement', '0001_initial'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confoturline',
            name='manifest_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shipments.manifestline'),
        ),
        migrations.AddField(
            model_name='confoturline',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procurement.quotation'),
        ),
        migrations.AddField(
            model_name='confoturlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confoturlist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confotur_lists', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='confoturline',
            name='confotur_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='customs.confoturlist'),
        ),
        migrations.AddField(
            model_name='confoturapproval',
            name='confotur_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='customs.confoturlist'),
        ),
        migrations.AddField(
            model_name='customsdeclaration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customsdeclaration',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.document'),
        ),
        migrations.AddField(
            model_name='customsdeclaration',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs_declarations', to='shipments.shipment'),
        ),
        migrations.AddField(
            model_name='customsdocumentlink',
            name='confotur_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='customs.confoturline'),
        ),
        migrations.AddField(
            model_name='customsdocumentlink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customsdocumentlink',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.document'),
        ),
        migrations.AddField(
            model_name='customsliquidation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customsliquidation',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidations', to='customs.customsdeclaration'),
        ),
        migrations.AddField(
            model_name='customsliquidation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.document'),
        ),
        migrations.AddField(
            model_name='exemptionallocation',
            name='confotur_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemption_allocations', to='customs.confoturline'),
        ),
        migrations.AddField(
            model_name='exemptionallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exemptionallocation',
            name='liquidation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemption_allocations', to='customs.customsliquidation'),
        ),
        migrations.AddField(
            model_name='importentry',
            name='confotur_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_entries', to='customs.confoturline'),
        ),
        migrations.AddField(
            model_name='importentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importentry',
            name='liquidation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_entries', to='customs.customsliquidation'),
        ),
        migrations.AddField(
            model_name='importentry',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_entries', to='shipments.shipment'),
        ),
    ]
