# Generated by Django 5.0.14 on 2026-07-19 04:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
        ('procurement', '0002_initial'),
        ('projects', '0002_building_building_number_floor_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='required_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='The actually-needed quantity, when known, for shortage calculation — never assumed equal to quantity_ordered when not explicitly recorded.', max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='OrderLineAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_scope', models.CharField(choices=[('organization', 'Toda la organización'), ('project', 'Todo el proyecto'), ('zone', 'Etapa o zona'), ('building', 'Edificio'), ('floor', 'Piso'), ('unit', 'Apartamento / unidad'), ('common_area', 'Área común'), ('warehouse_stock', 'Stock de almacén'), ('replacement_reserve', 'Reserva de reemplazo'), ('unknown_pending', 'Desconocido / pendiente de asignación')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reassignment_reason', models.TextField(blank=True)),
                ('reassigned_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.area')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.building')),
                ('building_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.buildingfamily')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('drawing', models.ForeignKey(blank=True, help_text='The exact drawing revision used for this allocation — never silently replaced by a later revision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drawings.drawing')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.floor')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='procurement.purchaseorderline')),
                ('reassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reassigned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_to_set', to='procurement.orderlineallocation')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedSpare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('compatible_typology', models.CharField(blank=True, help_text='Compatibility / intended typology.', max_length=255)),
                ('reason', models.TextField()),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_spares', to='procurement.purchaseorderline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
