# Generated by Django 5.0.14 on 2026-07-19 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_can_override_gates'),
        ('audit', '0003_alter_auditevent_action_evidencebundle_evidenceitem_and_more'),
        ('governance', '0001_initial'),
        ('procurement', '0003_purchaseorderline_required_quantity_and_more'),
        ('projects', '0002_building_building_number_floor_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='classification',
            field=models.CharField(blank=True, choices=[('china_internal', 'Interno China'), ('source_private', 'Privado de origen (fábrica)'), ('trading_company_confidential', 'Confidencial de la comercializadora'), ('supplier_shared', 'Compartido con proveedor'), ('client_project', 'Proyecto de cliente'), ('client_shared', 'Compartido con cliente'), ('operational_shared', 'Compartido operativo'), ('restricted_finance', 'Financiero restringido'), ('legal_required', 'Requerido legalmente')], default='operational_shared', max_length=40),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_kind',
            field=models.CharField(choices=[('standard', 'Estándar'), ('client', 'Orden de compra del cliente'), ('upstream_factory', 'Orden de compra a fábrica (aguas arriba)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='classification',
            field=models.CharField(blank=True, choices=[('china_internal', 'Interno China'), ('source_private', 'Privado de origen (fábrica)'), ('trading_company_confidential', 'Confidencial de la comercializadora'), ('supplier_shared', 'Compartido con proveedor'), ('client_project', 'Proyecto de cliente'), ('client_shared', 'Compartido con cliente'), ('operational_shared', 'Compartido operativo'), ('restricted_finance', 'Financiero restringido'), ('legal_required', 'Requerido legalmente')], default='operational_shared', max_length=40),
        ),
        migrations.AddField(
            model_name='quotation',
            name='factory_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_quotes', to='governance.party'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, help_text='Registered/production-site address — confidentiality-sensitive for hidden factories.'),
        ),
        migrations.CreateModel(
            name='ProcurementPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('visibility_mode', models.CharField(choices=[('controlled_transparency', 'Transparencia controlada'), ('controlled_confidentiality', 'Confidencialidad controlada')], default='controlled_confidentiality', help_text='For China-managed DT Beach procurement, CONTROLLED_CONFIDENTIALITY is the configured default.', max_length=40)),
                ('visibility_mode_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('frozen', 'Congelado'), ('closed', 'Cerrado')], default='draft', max_length=20)),
                ('is_frozen', models.BooleanField(default=False)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_snapshot', models.JSONField(blank=True, default=dict, help_text='Critical terms frozen at freeze time: role party ids, incoterm, currency, payment terms, specification/drawing revision, evidence policy — altering any of these afterward requires a governance.ChangeRequest, never a direct edit.')),
                ('is_on_hold', models.BooleanField(default=False, help_text='True while a Change Request against a frozen term is pending.')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The hosting/administering organization for this package.', on_delete=django.db.models.deletion.CASCADE, related_name='procurement_packages', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_packages', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='InternalCommercialSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('exchange_rate_note', models.CharField(blank=True, max_length=255)),
                ('inland_transport', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('inspection_qc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('consolidation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('duties_taxes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('administration', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contingency', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('markup_method', models.CharField(blank=True, help_text='E.g. "percentage_on_landed_cost", "fixed_fee".', max_length=50)),
                ('markup_value', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('recommended_sell_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_approval', 'Pendiente de aprobación'), ('approved', 'Aprobado')], default='draft', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('china_internal', 'Interno China'), ('source_private', 'Privado de origen (fábrica)'), ('trading_company_confidential', 'Confidencial de la comercializadora'), ('supplier_shared', 'Compartido con proveedor'), ('client_project', 'Proyecto de cliente'), ('client_shared', 'Compartido con cliente'), ('operational_shared', 'Compartido operativo'), ('restricted_finance', 'Financiero restringido'), ('legal_required', 'Requerido legalmente')], default='trading_company_confidential', max_length=40)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_sheets', to='procurement.quotation')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_commercial_sheets', to='procurement.procurementpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactoryRFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_spec', models.TextField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado'), ('quoted', 'Cotizado'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('classification', models.CharField(choices=[('china_internal', 'Interno China'), ('source_private', 'Privado de origen (fábrica)'), ('trading_company_confidential', 'Confidencial de la comercializadora'), ('supplier_shared', 'Compartido con proveedor'), ('client_project', 'Proyecto de cliente'), ('client_shared', 'Compartido con cliente'), ('operational_shared', 'Compartido operativo'), ('restricted_finance', 'Financiero restringido'), ('legal_required', 'Requerido legalmente')], default='source_private', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('factory_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_rfqs', to='governance.party')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_rfqs', to='procurement.procurementpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('client_facing_terms', models.TextField(blank=True)),
                ('delivery_terms', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado'), ('sent', 'Enviado al cliente')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('china_internal', 'Interno China'), ('source_private', 'Privado de origen (fábrica)'), ('trading_company_confidential', 'Confidencial de la comercializadora'), ('supplier_shared', 'Compartido con proveedor'), ('client_project', 'Proyecto de cliente'), ('client_shared', 'Compartido con cliente'), ('operational_shared', 'Compartido operativo'), ('restricted_finance', 'Financiero restringido'), ('legal_required', 'Requerido legalmente')], default='client_shared', max_length=40)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visible_seller_party', models.ForeignKey(blank=True, help_text='The client-visible seller of record, e.g. the trading company.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='governance.party')),
                ('source_internal_sheet', models.ForeignKey(blank=True, help_text='Internal traceability only — must never be exposed through any client-facing view/serializer/export.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_quotes', to='procurement.internalcommercialsheet')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_quotes', to='procurement.procurementpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_in_package', to='procurement.procurementpackage'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_quotes', to='procurement.procurementpackage'),
        ),
        migrations.CreateModel(
            name='VerificationAssertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assertion_code', models.SlugField(max_length=80)),
                ('client_visible_wording', models.TextField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('china_internal', 'Interno China'), ('source_private', 'Privado de origen (fábrica)'), ('trading_company_confidential', 'Confidencial de la comercializadora'), ('supplier_shared', 'Compartido con proveedor'), ('client_project', 'Proyecto de cliente'), ('client_shared', 'Compartido con cliente'), ('operational_shared', 'Compartido operativo'), ('restricted_finance', 'Financiero restringido'), ('legal_required', 'Requerido legalmente')], default='client_shared', max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_assertions', to='procurement.procurementpackage')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_evidence_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_assertions', to='audit.evidencebundle')),
                ('source_party', models.ForeignKey(blank=True, help_text='Hidden internally — never rendered in client_visible_wording.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='governance.party')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='procurement.verificationassertion')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
