# Generated by Django 5.0.14 on 2026-07-18 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAllocationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('quantity', 'Cantidad'), ('product_value', 'Valor de producto'), ('gross_weight', 'Peso bruto'), ('net_weight', 'Peso neto'), ('cbm', 'CBM'), ('package', 'Paquete'), ('container', 'Contenedor'), ('manual_percentage', 'Porcentaje manual'), ('manual_amount', 'Monto manual')], max_length=30)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('total_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_type', models.CharField(choices=[('freight', 'Flete internacional'), ('insurance', 'Seguro'), ('customs_duties', 'Aduanas y aranceles'), ('port_terminal', 'Cargos portuarios/terminal'), ('brokerage', 'Agenciamiento aduanal'), ('local_transport', 'Transporte local'), ('handling', 'Manejo'), ('storage', 'Almacenaje'), ('demurrage', 'Demora'), ('inspection', 'Inspección'), ('other', 'Otro')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice_reference', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='ISO 4217, e.g. USD, CNY, DOP.', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('rate_date', models.DateField()),
                ('source', models.CharField(blank=True, help_text='e.g. Yekalon PI stated rate, bank rate, etc.', max_length=150)),
            ],
            options={
                'ordering': ['-rate_date'],
            },
        ),
        migrations.CreateModel(
            name='LandedCostLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('base_currency_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('freight_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('local_cost_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('other_cost_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('final_landed_cost_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('total_landed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandedCostVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('is_final', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='CostAllocationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('basis_value', models.DecimalField(blank=True, decimal_places=4, help_text='The quantity/weight/CBM/value used as the allocation basis for this line.', max_digits=14, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
