# Generated by Django 5.0.14 on 2026-07-18 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cost', '0001_initial'),
        ('documents', '0001_initial'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costallocationline',
            name='manifest_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='shipments.manifestline'),
        ),
        migrations.AddField(
            model_name='costallocationrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costallocationrun',
            name='run_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costallocationrun',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocation_runs', to='shipments.shipment'),
        ),
        migrations.AddField(
            model_name='costallocationline',
            name='allocation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cost.costallocationrun'),
        ),
        migrations.AddField(
            model_name='costcharge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costallocationrun',
            name='cost_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_runs', to='cost.costcharge'),
        ),
        migrations.AddField(
            model_name='costdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.document'),
        ),
        migrations.AddField(
            model_name='costdocument',
            name='is_duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Set when the same cost invoice is detected submitted twice (spec section 26, acceptance case 27).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='cost.costdocument'),
        ),
        migrations.AddField(
            model_name='costdocument',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_documents', to='shipments.shipment'),
        ),
        migrations.AddField(
            model_name='costcharge',
            name='cost_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='cost.costdocument'),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costdocument',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cost.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='from_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='cost.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='to_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='cost.currency'),
        ),
        migrations.AddField(
            model_name='landedcostline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landedcostline',
            name='manifest_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_lines', to='shipments.manifestline'),
        ),
        migrations.AddField(
            model_name='landedcostversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landedcostversion',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landedcostversion',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_versions', to='shipments.shipment'),
        ),
        migrations.AddField(
            model_name='landedcostline',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cost.landedcostversion'),
        ),
        migrations.AlterUniqueTogether(
            name='landedcostversion',
            unique_together={('shipment', 'version_number')},
        ),
    ]
