# Generated by Django 5.0.14 on 2026-07-18 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentClassificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggested_language', models.CharField(blank=True, max_length=10)),
                ('confidence', models.CharField(choices=[('confirmed', 'Confirmado por persona'), ('high', 'Confianza alta (automático)'), ('medium', 'Confianza media (automático)'), ('low', 'Confianza baja (automático)'), ('unknown', 'Desconocido')], default='low', max_length=20)),
                ('method', models.CharField(blank=True, help_text='e.g. filename heuristic, OCR, manual rule', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentFieldSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('field_name', models.CharField(max_length=100)),
                ('source_reference', models.CharField(blank=True, help_text='Sheet/page/row/cell/package reference within the source document.', max_length=255)),
                ('source_value', models.TextField(blank=True, help_text='Exact original-language value. Never overwritten.')),
                ('extracted_value', models.TextField(blank=True)),
                ('normalized_value', models.TextField(blank=True)),
                ('proposed_translation', models.TextField(blank=True)),
                ('confirmed_translation', models.TextField(blank=True)),
                ('canonical_value', models.TextField(blank=True)),
                ('confidence', models.CharField(choices=[('confirmed', 'Confirmado por persona'), ('high', 'Confianza alta (automático)'), ('medium', 'Confianza media (automático)'), ('low', 'Confianza baja (automático)'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('warning', models.CharField(blank=True, max_length=255)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=60)),
                ('is_official_customs_document', models.BooleanField(default=False, help_text='True for BL, customs declarations, liquidations, CONFOTUR — documents that must be preserved exactly as issued and never treated as internal-only.')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias_text', models.CharField(max_length=150)),
                ('language', models.CharField(blank=True, help_text='e.g. es, en, zh', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('stored_name', models.CharField(help_text='Opaque on-disk name from the storage adapter.', max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('page_or_sheet_count', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['document', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='HumanConfirmedDocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequiredDocumentRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gate_name', models.CharField(help_text='E.g. "operational_verification".', max_length=100)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierDocumentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('column_mapping', models.JSONField(blank=True, default=dict, help_text='source column -> canonical field')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('human_confirmed_type', models.BooleanField(default=False, help_text='False if the type shown is only an automatic guess.')),
                ('title', models.CharField(max_length=255)),
                ('detected_language', models.CharField(blank=True, max_length=10)),
                ('confirmed_language', models.CharField(blank=True, max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
