# Generated by Django 5.0.14 on 2026-07-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='classification',
            field=models.CharField(blank=True, choices=[('china_internal', 'Interno China'), ('source_private', 'Privado de origen (fábrica)'), ('trading_company_confidential', 'Confidencial de la comercializadora'), ('supplier_shared', 'Compartido con proveedor'), ('client_project', 'Proyecto de cliente'), ('client_shared', 'Compartido con cliente'), ('operational_shared', 'Compartido operativo'), ('restricted_finance', 'Financiero restringido'), ('legal_required', 'Requerido legalmente')], default='operational_shared', max_length=40),
        ),
    ]
