# Generated by Django 5.0.14 on 2026-07-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_classification'),
        ('procurement', '0004_purchaseorder_classification_purchaseorder_po_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_in_package', to='procurement.procurementpackage'),
        ),
    ]
