# Generated by Django 5.0.14 on 2026-07-18 22:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0002_initial'),
        ('inventory', '0002_initial'),
        ('receiving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativestorageoption',
            options={'ordering': ['option_type', 'option_name']},
        ),
        migrations.RemoveField(
            model_name='alternativestorageoption',
            name='additional_transport_cost',
        ),
        migrations.RemoveField(
            model_name='alternativestorageoption',
            name='decided_by',
        ),
        migrations.RemoveField(
            model_name='alternativestorageoption',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='alternativestorageoption',
            name='receiving_plan',
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='access_controlled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='access_restrictions_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='capacity_volume_cbm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='capacity_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='climate_controlled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='contract_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='covered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cost.currency'),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='demurrage_penalty_estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='demurrage_penalty_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='dry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='inbound_transport_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='internal_location',
            field=models.ForeignKey(blank=True, help_text='Solo para option_type=internal_baseline — reutiliza la capacidad/idoneidad ya registrada de esta ubicación en vez de duplicarla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouselocation'),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='location_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='minimum_commitment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='operational_lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo operativo estimado para mover material hacia/desde esta opción.', null=True),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='option_type',
            field=models.CharField(choices=[('internal_baseline', 'Almacén propio (referencia)'), ('external_warehouse', 'Almacén externo'), ('port_storage', 'Almacenaje en puerto'), ('other', 'Otro')], default='external_warehouse', max_length=30),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='outbound_transport_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='secure',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alternativestorageoption',
            name='storage_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo total estimado de almacenaje para la duración evaluada, no una tarifa diaria.', max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='StorageComparisonScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('version_number', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('finalized', 'Finalizado')], default='draft', max_length=20)),
                ('recommendation_rationale', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('chosen_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='receiving.alternativestorageoption')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receiving_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_comparison_scenarios', to='receiving.receivingplan')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('receiving_plan', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='alternativestorageoption',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='receiving.storagecomparisonscenario'),
        ),
    ]
