# Generated by Django 5.0.14 on 2026-07-19 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_role_can_override_gates'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0002_initial'),
        ('projects', '0002_building_building_number_floor_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnclassifiedEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('classification_status', models.CharField(choices=[('unclassified', 'Sin clasificar'), ('partially_classified', 'Parcialmente clasificado'), ('classified', 'Clasificado')], default='unclassified', max_length=30)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unclassified_evidence', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'unclassified evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='evidenceinbox.evidenceclassification')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='evidenceinbox.unclassifiedevidence')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='evidenceinb_content_d9e6d4_idx')],
            },
        ),
    ]
