# Generated by Django 5.0.14 on 2026-07-18 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscrepancyResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_note', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left_object_id', models.UUIDField()),
                ('right_object_id', models.UUIDField()),
                ('status', models.CharField(choices=[('exact', 'Exacto'), ('strong_candidate', 'Candidato fuerte'), ('possible_candidate', 'Candidato posible'), ('manually_confirmed', 'Confirmado manualmente'), ('unmatched', 'Sin coincidencia'), ('conflict', 'Conflicto'), ('superseded', 'Reemplazado')], default='possible_candidate', max_length=30)),
                ('confidence', models.CharField(choices=[('confirmed', 'Confirmado por persona'), ('high', 'Confianza alta (automático)'), ('medium', 'Confianza media (automático)'), ('low', 'Confianza baja (automático)'), ('unknown', 'Desconocido')], default='medium', max_length=20)),
                ('agreeing_fields', models.JSONField(blank=True, default=list)),
                ('conflicting_fields', models.JSONField(blank=True, default=list)),
                ('quantity_relationship', models.CharField(blank=True, max_length=255)),
                ('explanation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuantityReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_required', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_quoted', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_ordered', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_paid_for', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_produced', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_packed', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_shipped', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_expected_at_receipt', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_received', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_accepted', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_damaged', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_missing', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_available', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_installed', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waived_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfirmedMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discrepancy_type', models.CharField(choices=[('required_not_ordered', 'Requerido pero no ordenado'), ('ordered_not_invoiced', 'Ordenado pero no facturado'), ('invoiced_not_packed', 'Facturado pero no empacado'), ('packed_not_invoiced', 'Empacado pero no facturado'), ('packed_quantity_mismatch', 'Empacado por debajo/encima de lo ordenado'), ('duplicate_line_or_package', 'Línea o paquete duplicado'), ('unit_conflict', 'Conflicto de unidad'), ('dimension_conflict', 'Conflicto de dimensión'), ('color_conflict', 'Conflicto de color'), ('orientation_conflict', 'Conflicto izquierda/derecha'), ('price_currency_conflict', 'Conflicto de precio/moneda'), ('project_building_conflict', 'Conflicto de proyecto/edificio'), ('missing_package_id', 'Falta identificador de paquete'), ('missing_container_assignment', 'Falta asignación de contenedor'), ('bl_container_mismatch', 'Discrepancia BL/contenedor'), ('official_vs_operational_mismatch', 'Discrepancia manifiesto oficial vs. operativo'), ('internal_cargo_not_represented', 'Carga interna no representada oficialmente'), ('open_commitment_closed_incorrectly', 'Compromiso abierto cerrado incorrectamente'), ('prior_fulfillment_unverified', 'Cumplimiento previo sin evidencia verificada'), ('replacement_counted_as_new', 'Reemplazo contado como compra nueva'), ('added_at_loading_without_review', 'Agregado en carga sin revisión aduanal'), ('weight_cbm_mismatch', 'Discrepancia de peso o CBM'), ('missing_document', 'Documento faltante'), ('revision_conflict', 'Conflicto de revisión'), ('receipt_shortage', 'Faltante en recepción'), ('receipt_overage', 'Sobrante en recepción'), ('damage', 'Daño'), ('wrong_destination', 'Destino incorrecto'), ('inventory_issued_wrong_building', 'Inventario emitido a edificio incorrecto'), ('incomplete_kit', 'Ensamble/kit incompleto'), ('confotur_duplicate_or_omission', 'Duplicado u omisión CONFOTUR'), ('identity_conflict', 'Conflicto de identidad de producto (p.ej. plancha vs. tope)')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='warning', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('blocks_gate', models.CharField(blank=True, help_text='Gate name this discrepancy blocks while unresolved, if any.', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'discrepancies',
                'ordering': ['-severity', '-created_at'],
            },
        ),
    ]
