# Generated by Django 5.0.14 on 2026-07-19 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        ('projects', '0002_building_building_number_floor_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drawing_type', models.CharField(choices=[('site_plan', 'Plano de conjunto'), ('building_plan', 'Plano de edificio'), ('floor_plan', 'Plano de piso'), ('unit_typology', 'Tipología de unidad/apartamento'), ('room_detail', 'Plano de detalle/ambiente')], max_length=30)),
                ('discipline', models.CharField(choices=[('architectural', 'Arquitectónico'), ('structural', 'Estructural'), ('electrical', 'Eléctrico'), ('sanitary', 'Sanitario'), ('other', 'Otro')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('drawing_number', models.CharField(blank=True, max_length=100)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reference', 'Referencia'), ('draft', 'Borrador'), ('under_review', 'En revisión'), ('approved', 'Aprobado'), ('signed_stamped', 'Firmado/Sellado'), ('issued_for_order', 'Emitido para orden'), ('issued_for_construction', 'Emitido para construcción'), ('executed_as_built', 'Ejecutado / Tal como construido'), ('superseded', 'Reemplazado')], default='draft', max_length=30)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='projects.building')),
                ('building_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='projects.buildingfamily')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='projects.floor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='projects.project')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.document')),
                ('supersedes', models.OneToOneField(blank=True, help_text='The exact prior revision this one replaces — that row is never edited, only marked superseded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='drawings.drawing')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='projects.unit')),
            ],
            options={
                'ordering': ['-revision', 'title'],
            },
        ),
    ]
