# Generated by Django 5.0.14 on 2026-07-18 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Recepción'), ('provisional_receipt', 'Recepción provisional'), ('quarantine', 'Cuarentena'), ('release_from_quarantine', 'Liberación de cuarentena'), ('put_away', 'Ubicación (put-away)'), ('transfer', 'Transferencia'), ('reservation', 'Reserva'), ('pick', 'Picking'), ('dispatch', 'Despacho'), ('project_delivery', 'Entrega a proyecto'), ('return', 'Devolución'), ('adjustment', 'Ajuste'), ('damage', 'Daño'), ('write_off', 'Baja'), ('installation_consumption', 'Consumo por instalación'), ('reclassification', 'Reclasificación'), ('historical_opening_balance', 'Saldo inicial histórico')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positive = increases on-hand at to_location.', max_digits=14)),
                ('intended_destination_scope', models.CharField(blank=True, max_length=30)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('requires_approval', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, help_text='Prevents duplicate submission from double-posting the same movement (spec section 32).', max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available_volume_cbm', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('available_area_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('weight_capacity_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationSuitability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('covered', models.BooleanField(default=False)),
                ('dry', models.BooleanField(default=False)),
                ('climate_controlled', models.BooleanField(default=False)),
                ('secure', models.BooleanField(default=False)),
                ('access_controlled', models.BooleanField(default=False)),
                ('flood_risk', models.BooleanField(default=False)),
                ('leak_risk', models.BooleanField(default=False)),
                ('sun_exposure', models.BooleanField(default=False)),
                ('rain_exposure', models.BooleanField(default=False)),
                ('floor_load_kg_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('truck_access', models.BooleanField(default=False)),
                ('telehandler_access', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuarantineRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(max_length=255)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('site_type', models.CharField(choices=[('central_warehouse', 'Almacén central'), ('temporary_warehouse', 'Almacén temporal'), ('project_building', 'Edificio de proyecto'), ('outdoor_yard', 'Patio exterior'), ('covered_exterior', 'Exterior techado'), ('port_storage', 'Almacenaje portuario'), ('external_warehouse', 'Almacén externo'), ('container', 'Contenedor'), ('quarantine_area', 'Zona de cuarentena'), ('dispatch_staging', 'Zona de despacho')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('is_blind_count', models.BooleanField(default=True)),
                ('assigned_counter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(max_length=255)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('physical_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('recounted', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cycle_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.cyclecount')),
                ('approved_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventoryadjustment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_code', models.CharField(blank=True, max_length=100)),
                ('bought_for_scope', models.CharField(blank=True, help_text='DestinationScope at creation time.', max_length=30)),
                ('bought_for_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
