# Generated by Django 5.0.14 on 2026-07-18 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('inventory', '0001_initial'),
        ('items', '0001_initial'),
        ('projects', '0001_initial'),
        ('receiving', '0001_initial'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylot',
            name='source_receipt_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='receiving.receiptline'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.inventorylot'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventorylot'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='actual_destination_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.building'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventorylot'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='items.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='resulting_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventorymovement'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.inventorylot'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='material_request_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='requests.materialrequestline'),
        ),
        migrations.AddField(
            model_name='locationcapacity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationsuitability',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarantinerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarantinerecord',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_records', to='inventory.inventorylot'),
        ),
        migrations.AddField(
            model_name='quarantinerecord',
            name='placed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarantinerecord',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagesite',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.building'),
        ),
        migrations.AddField(
            model_name='storagesite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagesite',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagesite',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_sites', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='storagesite',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project'),
        ),
        migrations.AddField(
            model_name='cyclecount',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_counts', to='inventory.storagesite'),
        ),
        migrations.AddField(
            model_name='warehouselocation',
            name='allowed_categories',
            field=models.ManyToManyField(blank=True, related_name='+', to='items.productcategory'),
        ),
        migrations.AddField(
            model_name='warehouselocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarantinerecord',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.warehouselocation'),
        ),
        migrations.AddField(
            model_name='locationsuitability',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suitability', to='inventory.warehouselocation'),
        ),
        migrations.AddField(
            model_name='locationcapacity',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='inventory.warehouselocation'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_out', to='inventory.warehouselocation'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_in', to='inventory.warehouselocation'),
        ),
        migrations.AddField(
            model_name='warehousezone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousezone',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='inventory.storagesite'),
        ),
        migrations.AddField(
            model_name='warehouselocation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehousezone'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousezone',
            unique_together={('site', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouselocation',
            unique_together={('zone', 'code')},
        ),
    ]
