# Generated by Django 5.0.14 on 2026-07-19 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('procurement', '0003_purchaseorderline_required_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylot',
            name='purchased_spare',
            field=models.ForeignKey(blank=True, help_text='Set when this lot was received against an authorized purchased-spare confirmation — quantity received/available/reserved/consumed are still read from the ledger, never duplicated here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_lots', to='procurement.purchasedspare'),
        ),
    ]
