# Generated by Django 5.0.14 on 2026-07-18 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_can_override_gates'),
        ('documents', '0002_initial'),
        ('projects', '0001_initial'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='inspectionrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='installationrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectreceipt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='acceptancerecord',
            name='conditions_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='acceptancerecord',
            name='decision',
            field=models.CharField(choices=[('accepted', 'Aceptado'), ('conditional', 'Aceptado condicionado')], default='accepted', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text="When the delivery was actually recorded as completed at site, distinct from `Dispatch.dispatched_at` (warehouse release) and from this row's own creation time.", null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_location_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='quantity_damaged',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Damaged-on-delivery quantity — a subset of quantity_rejected, tracked separately so damage (a claim/quarantine concern) is never conflated with a plain refusal.', max_digits=14),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='inspected_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='previous_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinspections', to='requests.inspectionrecord'),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='result',
            field=models.CharField(blank=True, choices=[('pass', 'Aprobado'), ('conditional_pass', 'Aprobado condicionado'), ('fail', 'Rechazado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='technical_sign_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='technical_sign_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='assigned_installer',
            field=models.ForeignKey(blank=True, help_text='Installer or installation-team lead assigned/scheduled for this work.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='delivery_line',
            field=models.ForeignKey(blank=True, help_text='The specific delivered product/quantity this record is for — completes the project/building/floor/unit/product/delivered-quantity/delivery-record traceability chain.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installation_records', to='requests.deliveryline'),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='installer_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='False while work is still in progress or explicitly left incomplete.'),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='missing_components_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='quantity_damaged',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='quantity_not_used',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='requires_rework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='supervisor_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='supervisor_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Common-area destination, when the request is not for a specific unit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.area'),
        ),
        migrations.AddField(
            model_name='projectreceipt',
            name='confirmed_destination_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.area'),
        ),
        migrations.AlterField(
            model_name='inspectionrecord',
            name='passed',
            field=models.BooleanField(blank=True, help_text='Kept in sync with `result` (PASS/CONDITIONAL_PASS -> True, FAIL -> False) because apps.workflow.gates.evaluate_inspection_to_acceptance depends on this exact field — never duplicate that check, only keep this derived value correct.', null=True),
        ),
        migrations.AlterField(
            model_name='installationrecord',
            name='installed_at',
            field=models.DateTimeField(blank=True, help_text='Completion timestamp.', null=True),
        ),
        migrations.AlterField(
            model_name='installationrecord',
            name='photo_document',
            field=models.ForeignKey(blank=True, help_text='Primary photo, kept for backward compatibility — use the generic apps.audit.Attachment (content_type/object_id) for any additional evidence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='installationrecord',
            name='quantity_installed',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('reserved', 'Reservada'), ('picked', 'Recogida (picking)'), ('dispatched', 'Despachada'), ('partially_delivered', 'Entregada parcialmente'), ('delivered', 'Entregada'), ('closed', 'Cerrada')], default='submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='PunchListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='warning', max_length=20)),
                ('is_blocking', models.BooleanField(default=True, help_text='Critical defects default to blocking; a non-blocking (informational/minor) item can be created for tracking without preventing acceptance.')),
                ('correction_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_list_items', to='requests.inspectionrecord')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_blocking', 'correction_deadline'],
            },
        ),
    ]
