# Generated by Django 5.0.14 on 2026-07-18 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('requests', '0002_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchline',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Which specific reservation this dispatch quantity was drawn from — lets a single request line be split across several lots/reservations without ever dispatching more than any one reservation actually holds.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_lines', to='inventory.inventoryreservation'),
        ),
    ]
