# Generated by Django 5.0.14 on 2026-07-18 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_can_override_gates'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('reason', models.TextField()),
                ('before_state', models.JSONField(default=dict, help_text='The blocking GateResult at the moment of override.')),
                ('after_state', models.JSONField(default=dict, help_text='Handoff status/fields immediately after the override was applied.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='handoff',
            name='organization',
            field=models.ForeignKey(blank=True, help_text="Denormalized at creation time from the target object, same rationale as `project` below — every other view in this codebase scopes queries by organization and this keeps the inbox consistent. Always populated by apps.workflow.services.create_handoff(); nullable only to match this codebase's existing convention for denormalized cross-reference fields.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='handoff',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Denormalized at creation time from the target object (when it has a resolvable project) so the inbox can filter and enforce cross-project isolation without walking a different relation chain per target model type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project'),
        ),
        migrations.AddField(
            model_name='handoff',
            name='readiness_ready',
            field=models.BooleanField(default=False, help_text='Result of the last gate evaluation at submission time.'),
        ),
        migrations.AddField(
            model_name='handoff',
            name='readiness_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Full structured GateResult (unmet requirements, discrepancies, missing docs, etc.) frozen at the moment of submission, so the reviewing party sees exactly what was true then.'),
        ),
        migrations.AddField(
            model_name='handoff',
            name='supersedes',
            field=models.ForeignKey(blank=True, help_text='Set when this handoff is a corrected resubmission of a rejected/returned one — the prior row is marked SUPERSEDED and kept forever, never edited or deleted (core principle 4.4).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='workflow.handoff'),
        ),
        migrations.CreateModel(
            name='GateDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='Matched against the apps.workflow.gates registry, e.g. "logistics_to_receiving".', max_length=60)),
                ('name', models.CharField(max_length=150)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_definitions', to='accounts.organization')),
                ('required_role_to_accept', models.ForeignKey(blank=True, help_text='If set, only a user holding this role may accept a handoff created against this gate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.role')),
                ('target_content_type', models.ForeignKey(help_text='The model type this gate evaluates readiness for (e.g. Shipment, MaterialRequest, InstallationRecord).', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department')),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstage')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='handoff',
            name='gate_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs', to='workflow.gatedefinition'),
        ),
        migrations.AddIndex(
            model_name='handoff',
            index=models.Index(fields=['project'], name='workflow_ha_project_e4c794_idx'),
        ),
        migrations.AddIndex(
            model_name='handoff',
            index=models.Index(fields=['to_department', 'status'], name='workflow_ha_to_depa_b82814_idx'),
        ),
        migrations.AddConstraint(
            model_name='handoff',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['not_ready', 'ready_for_submission', 'submitted'])), fields=('content_type', 'object_id', 'gate_definition'), name='unique_active_handoff_per_target_gate'),
        ),
        migrations.AddField(
            model_name='gateoverride',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='gateoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gateoverride',
            name='gate_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='workflow.gatedefinition'),
        ),
        migrations.AddField(
            model_name='gateoverride',
            name='handoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_used', to='workflow.handoff'),
        ),
        migrations.AddField(
            model_name='gateoverride',
            name='overridden_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gatedefinition',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='gateoverride',
            index=models.Index(fields=['content_type', 'object_id'], name='workflow_ga_content_0b8584_idx'),
        ),
    ]
