# Generated by Django 5.0.14 on 2026-07-19 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_gateoverride_handoff_organization_handoff_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gateoverride',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiration — the override no longer applies after this time.', null=True),
        ),
        migrations.AddField(
            model_name='gateoverride',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateoverride',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
