# Generated by Django 5.0.14 on 2026-07-19 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_role_can_override_gates'),
        ('documents', '0002_initial'),
        ('drawings', '0001_initial'),
        ('fieldissues', '0002_fieldissue_training_session'),
        ('items', '0001_initial'),
        ('procurement', '0003_purchaseorderline_required_quantity_and_more'),
        ('projects', '0002_building_building_number_floor_label_and_more'),
        ('shipments', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkthroughCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=60)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkthrough_categories', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'walkthrough categories',
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Walkthrough',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('construction_progress', 'Recorrido de progreso de construcción'), ('quality_control', 'Recorrido de control de calidad'), ('training_reference', 'Recorrido de capacitación/instalación de referencia'), ('pre_delivery_final', 'Recorrido previo a la entrega final'), ('final_handover_delivery', 'Recorrido de entrega/traspaso final'), ('reinspection', 'Recorrido de reinspección')], max_length=30)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('progress_status', models.CharField(choices=[('not_started', 'No iniciado'), ('in_progress', 'En progreso'), ('completed', 'Completado')], default='not_started', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('delivery_decision', models.CharField(choices=[('pending', 'Pendiente'), ('ready', 'Listo para entrega'), ('not_ready', 'No listo para entrega')], default='pending', max_length=20)),
                ('delivery_decided_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_override_reason', models.TextField(blank=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.area')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='walkthroughs', to='projects.building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivery_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('delivery_overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drawings.drawing')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.floor')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='walkthroughs_attended', to=settings.AUTH_USER_MODEL)),
                ('previous_walkthrough', models.ForeignKey(blank=True, help_text='Set for a reinspection walkthrough — the prior attempt is never edited, only referenced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_walkthroughs', to='walkthroughs.walkthrough')),
                ('training_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walkthroughs', to='training.trainingsession')),
                ('unit', models.ForeignKey(blank=True, help_text='Primary/single unit for a one-apartment walkthrough.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walkthroughs', to='projects.unit')),
                ('units', models.ManyToManyField(blank=True, help_text='Additional units when this walkthrough covers a selected group of apartments.', related_name='group_walkthroughs', to='projects.unit')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='walkthroughs.walkthroughcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkthroughChecklistTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_template_items', to='walkthroughs.walkthroughcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'description'],
            },
        ),
        migrations.CreateModel(
            name='WalkthroughItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_or_location', models.CharField(blank=True, max_length=255)),
                ('component_description', models.CharField(blank=True, max_length=255)),
                ('checklist_result', models.CharField(choices=[('pass', 'Aprobado'), ('conditional', 'Aprobado condicionado'), ('fail', 'Rechazado'), ('not_applicable', 'No aplica'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('measurement', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('measurement_unit', models.CharField(blank=True, max_length=30)),
                ('digital_level_reading', models.CharField(blank=True, max_length=100)),
                ('level_condition', models.CharField(choices=[('ok', 'Correcto'), ('not_ok', 'Incorrecto'), ('not_applicable', 'No aplica'), ('not_checked', 'No verificado')], default='not_checked', max_length=20)),
                ('plumb_condition', models.CharField(choices=[('ok', 'Correcto'), ('not_ok', 'Incorrecto'), ('not_applicable', 'No aplica'), ('not_checked', 'No verificado')], default='not_checked', max_length=20)),
                ('square_condition', models.CharField(choices=[('ok', 'Correcto'), ('not_ok', 'Incorrecto'), ('not_applicable', 'No aplica'), ('not_checked', 'No verificado')], default='not_checked', max_length=20)),
                ('operational_test', models.CharField(choices=[('ok', 'Correcto'), ('not_ok', 'Incorrecto'), ('not_applicable', 'No aplica'), ('not_checked', 'No verificado')], default='not_checked', max_length=20)),
                ('condition_found', models.TextField(blank=True)),
                ('adjustment_performed', models.TextField(blank=True)),
                ('condition_after_adjustment', models.TextField(blank=True, help_text='Never overwrites `condition_found` — both are preserved distinctly.')),
                ('remaining_defect', models.TextField(blank=True)),
                ('is_blocking_defect', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shipments.container')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('field_issue', models.ForeignKey(blank=True, help_text='The corrective issue created from this item, if any — the correction/verification lifecycle itself lives entirely on FieldIssue, never duplicated here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fieldissues.fieldissue')),
                ('installer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='items.item')),
                ('purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procurement.purchaseorderline')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procurement.supplier')),
                ('unit', models.ForeignKey(blank=True, help_text='Which specific unit this item belongs to, when the parent walkthrough spans more than one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.unit')),
                ('walkthrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='walkthroughs.walkthrough')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkthroughItemEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('before', 'Antes'), ('during', 'Durante'), ('after', 'Después')], max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.document')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='walkthroughs.walkthroughitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
