# Generated by Django 5.0.14 on 2026-07-19 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitplans', '0001_initial'),
        ('walkthroughs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthroughitem',
            name='plan_template',
            field=models.ForeignKey(blank=True, help_text='Set when this item was created from the interactive apartment plan — kept even if later superseded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='unitplans.unitplantemplate'),
        ),
        migrations.AddField(
            model_name='walkthroughitem',
            name='plan_zone',
            field=models.ForeignKey(blank=True, help_text='The exact room/zone clicked to create this walkthrough item — immutable source-location reference.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='unitplans.planzone'),
        ),
    ]
