# Generated by Django 5.0.14 on 2026-07-18 22:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_role_can_override_gates'),
        ('cost', '0002_initial'),
        ('inventory', '0002_initial'),
        ('items', '0001_initial'),
        ('matching', '0002_initial'),
        ('procurement', '0002_initial'),
        ('receiving', '0002_alter_alternativestorageoption_options_and_more'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('claim_type', models.CharField(choices=[('shortage', 'Faltante'), ('overage', 'Sobrante no solicitado'), ('damage', 'Daño'), ('wrong_item', 'Artículo incorrecto'), ('quality_defect', 'Defecto de calidad'), ('missing_component', 'Componente faltante'), ('other', 'Otro')], max_length=30)),
                ('reason', models.TextField()),
                ('quantity_claimed', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_damaged', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('quantity_missing', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('approved', 'Aprobado para envío'), ('submitted', 'Enviado al proveedor'), ('supplier_responded', 'Proveedor respondió'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='draft', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_response', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('partially_accepted', 'Parcialmente aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=30)),
                ('supplier_response_date', models.DateField(blank=True, null=True)),
                ('supplier_response_notes', models.TextField(blank=True)),
                ('resolution_type', models.CharField(choices=[('none', 'Ninguna'), ('replacement', 'Reemplazo'), ('credit_note', 'Nota de crédito'), ('settlement', 'Pago/Liquidación')], default='none', max_length=30)),
                ('resolution_reference', models.CharField(blank=True, max_length=150)),
                ('resolution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='shipments.container')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cost.currency')),
                ('discrepancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='matching.discrepancy')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='receiving.inspection')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='items.item')),
                ('manifest_variance', models.ForeignKey(blank=True, help_text='Links to the existing Official-vs-Operational variance record — never overwritten or duplicated here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='shipments.manifestvariance')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_claims', to='accounts.organization')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='procurement.purchaseorder')),
                ('purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='procurement.purchaseorderline')),
                ('quarantine_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='inventory.quarantinerecord')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='receiving.receipt')),
                ('receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='receiving.receiptline')),
                ('replacement_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='shipments.replacementcase')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible_internal_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible_supplier_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procurement.suppliercontact')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='shipments.shipment')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='procurement.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
