# Generated by Django 5.0.14 on 2026-07-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldissues', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldissue',
            name='training_session',
            field=models.ForeignKey(blank=True, help_text='Set when this issue was created directly from a training session — preserves the relationship.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_issues', to='training.trainingsession'),
        ),
    ]
