# Generated by Django 5.0.14 on 2026-07-19 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldissues', '0002_fieldissue_training_session'),
        ('walkthroughs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldissue',
            name='walkthrough_item',
            field=models.ForeignKey(blank=True, help_text='Set when this issue was created directly from a walkthrough inspection item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='walkthroughs.walkthroughitem'),
        ),
    ]
