# Generated by Django 5.0.14 on 2026-07-18 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('document_upload', 'Carga de documento'), ('document_replacement', 'Reemplazo de documento'), ('import_confirmation', 'Confirmación de importación'), ('match_confirmation', 'Confirmación de coincidencia'), ('match_reversal', 'Reversión de coincidencia'), ('waiver', 'Dispensa'), ('handoff', 'Entrega de responsabilidad'), ('payment_approval', 'Aprobación de pago'), ('origin_release', 'Liberación de origen'), ('receiving_plan_approval', 'Aprobación de plan de recepción'), ('operational_release', 'Liberación operativa'), ('receipt_posting', 'Registro de recepción'), ('quarantine', 'Cuarentena'), ('quarantine_release', 'Liberación de cuarentena'), ('inventory_movement', 'Movimiento de inventario'), ('adjustment', 'Ajuste'), ('dispatch', 'Despacho'), ('project_acceptance', 'Aceptación de proyecto'), ('destination_reassignment', 'Reasignación de destino'), ('installation', 'Instalación'), ('acceptance', 'Aceptación'), ('cost_finalization', 'Finalización de costo'), ('claim_action', 'Acción de reclamo'), ('share_link_created', 'Enlace compartido creado'), ('share_link_revoked', 'Enlace compartido revocado'), ('other', 'Otro')], max_length=40)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=255)),
                ('link_path', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
