# Generated by Django 5.0.14 on 2026-07-19 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('document_upload', 'Carga de documento'), ('document_replacement', 'Reemplazo de documento'), ('import_confirmation', 'Confirmación de importación'), ('match_confirmation', 'Confirmación de coincidencia'), ('match_reversal', 'Reversión de coincidencia'), ('waiver', 'Dispensa'), ('handoff', 'Entrega de responsabilidad'), ('payment_approval', 'Aprobación de pago'), ('origin_release', 'Liberación de origen'), ('receiving_plan_approval', 'Aprobación de plan de recepción'), ('operational_release', 'Liberación operativa'), ('receipt_posting', 'Registro de recepción'), ('quarantine', 'Cuarentena'), ('quarantine_release', 'Liberación de cuarentena'), ('inventory_movement', 'Movimiento de inventario'), ('adjustment', 'Ajuste'), ('dispatch', 'Despacho'), ('project_acceptance', 'Aceptación de proyecto'), ('destination_reassignment', 'Reasignación de destino'), ('installation', 'Instalación'), ('acceptance', 'Aceptación'), ('cost_finalization', 'Finalización de costo'), ('claim_action', 'Acción de reclamo'), ('share_link_created', 'Enlace compartido creado'), ('share_link_revoked', 'Enlace compartido revocado'), ('role_assignment', 'Asignación de rol'), ('capability_grant', 'Otorgamiento de capacidad'), ('disclosure_grant', 'Otorgamiento de divulgación'), ('disclosure_revoked', 'Revocación de divulgación'), ('visibility_mode_change', 'Cambio de modo de visibilidad'), ('package_freeze', 'Congelamiento de paquete'), ('change_request', 'Solicitud de cambio'), ('verification_assertion', 'Aserción de verificación'), ('evidence_verification', 'Verificación de evidencia'), ('privileged_access_granted', 'Acceso privilegiado concedido'), ('privileged_access_denied', 'Acceso privilegiado denegado'), ('risk_flag', 'Señal de riesgo'), ('derived_artifact', 'Artefacto derivado'), ('other', 'Otro')], max_length=40),
        ),
        migrations.CreateModel(
            name='EvidenceBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('bundle_type', models.CharField(choices=[('production_verification', 'Verificación de producción'), ('quality_control', 'Control de calidad'), ('packing', 'Empaque'), ('receiving', 'Recepción'), ('shipment', 'Embarque'), ('installation', 'Instalación'), ('walkthrough', 'Recorrido'), ('approval', 'Aprobación'), ('other', 'Otro (configurable)')], default='other', max_length=40)),
                ('required_evidence_types', models.JSONField(blank=True, default=list)),
                ('minimum_count', models.PositiveIntegerField(default=1)),
                ('required_verifier_capability', models.CharField(blank=True, default='VERIFY_EVIDENCE', max_length=60)),
                ('minimum_review_state', models.CharField(default='verified', max_length=20)),
                ('requires_geolocation', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('incomplete', 'Incompleto'), ('complete', 'Completo (sin verificar)'), ('verified', 'Verificado')], default='incomplete', max_length=20)),
                ('classification', models.CharField(blank=True, choices=[('china_internal', 'Interno China'), ('source_private', 'Privado de origen (fábrica)'), ('trading_company_confidential', 'Confidencial de la comercializadora'), ('supplier_shared', 'Compartido con proveedor'), ('client_project', 'Proyecto de cliente'), ('client_shared', 'Compartido con cliente'), ('operational_shared', 'Compartido operativo'), ('restricted_finance', 'Financiero restringido'), ('legal_required', 'Requerido legalmente')], default='operational_shared', max_length=40)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(blank=True, max_length=100)),
                ('capture_method', models.CharField(blank=True, help_text='photo, scan, manual, ...', max_length=50)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('device_metadata', models.JSONField(blank=True, default=dict)),
                ('location', models.CharField(blank=True, help_text='Free-text location, only when lawfully captured.', max_length=255)),
                ('classification', models.CharField(blank=True, choices=[('china_internal', 'Interno China'), ('source_private', 'Privado de origen (fábrica)'), ('trading_company_confidential', 'Confidencial de la comercializadora'), ('supplier_shared', 'Compartido con proveedor'), ('client_project', 'Proyecto de cliente'), ('client_shared', 'Compartido con cliente'), ('operational_shared', 'Compartido operativo'), ('restricted_finance', 'Financiero restringido'), ('legal_required', 'Requerido legalmente')], default='operational_shared', max_length=40)),
                ('review_status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('verified', 'Verificado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verification_basis', models.TextField(blank=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audit.evidencebundle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='evidencebundle',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_evide_content_5d120e_idx'),
        ),
    ]
