# Generated by Django 5.0.14 on 2026-07-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditevent_action_evidencebundle_evidenceitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('document_upload', 'Carga de documento'), ('document_replacement', 'Reemplazo de documento'), ('import_confirmation', 'Confirmación de importación'), ('match_confirmation', 'Confirmación de coincidencia'), ('match_reversal', 'Reversión de coincidencia'), ('waiver', 'Dispensa'), ('handoff', 'Entrega de responsabilidad'), ('payment_approval', 'Aprobación de pago'), ('origin_release', 'Liberación de origen'), ('receiving_plan_approval', 'Aprobación de plan de recepción'), ('operational_release', 'Liberación operativa'), ('receipt_posting', 'Registro de recepción'), ('quarantine', 'Cuarentena'), ('quarantine_release', 'Liberación de cuarentena'), ('inventory_movement', 'Movimiento de inventario'), ('adjustment', 'Ajuste'), ('dispatch', 'Despacho'), ('project_acceptance', 'Aceptación de proyecto'), ('destination_reassignment', 'Reasignación de destino'), ('installation', 'Instalación'), ('acceptance', 'Aceptación'), ('cost_finalization', 'Finalización de costo'), ('claim_action', 'Acción de reclamo'), ('share_link_created', 'Enlace compartido creado'), ('share_link_revoked', 'Enlace compartido revocado'), ('role_assignment', 'Asignación de rol'), ('capability_grant', 'Otorgamiento de capacidad'), ('disclosure_grant', 'Otorgamiento de divulgación'), ('disclosure_revoked', 'Revocación de divulgación'), ('visibility_mode_change', 'Cambio de modo de visibilidad'), ('package_freeze', 'Congelamiento de paquete'), ('change_request', 'Solicitud de cambio'), ('verification_assertion', 'Aserción de verificación'), ('evidence_verification', 'Verificación de evidencia'), ('privileged_access_granted', 'Acceso privilegiado concedido'), ('privileged_access_denied', 'Acceso privilegiado denegado'), ('risk_flag', 'Señal de riesgo'), ('derived_artifact', 'Artefacto derivado'), ('gate_policy_created', 'Política de gate creada'), ('gate_policy_version_published', 'Versión de política de gate publicada'), ('gate_policy_version_withdrawn', 'Versión de política de gate retirada'), ('gate_policy_pinned', 'Política de gate fijada al paquete'), ('gate_progression_exemption_granted', 'Exención de progresión de gates otorgada'), ('other', 'Otro')], max_length=40),
        ),
    ]
