# Generated by Django 5.0.14 on 2026-07-18 12:08

import apps.reports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('shipment_dossier', 'Expediente completo de embarque'), ('matching_matrix', 'Matriz de coincidencias'), ('discrepancy_report', 'Reporte de discrepancias'), ('expected_receiving_packet', 'Paquete esperado de recepción'), ('actual_receiving_report', 'Reporte real de recepción'), ('container_closure_act', 'Acta de cierre de contenedor'), ('landed_cost_report', 'Reporte de costo de importación'), ('inventory_movement_history', 'Historial de movimientos de inventario'), ('current_inventory', 'Inventario actual'), ('kit_completeness', 'Completitud de kits'), ('project_request_history', 'Historial de solicitudes de proyecto'), ('destination_reassignment_report', 'Reporte de reasignación de destino'), ('installation_acceptance_history', 'Historial de instalación/aceptación'), ('claim_package', 'Paquete de reclamo'), ('confotur_reconciliation', 'Conciliación CONFOTUR'), ('responsibility_handoff_timeline', 'Línea de tiempo de responsabilidad'), ('full_traceability_timeline', 'Línea de tiempo de trazabilidad completa'), ('html_snapshot', 'Instantánea HTML autónoma')], max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rendered_html_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecureShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.reports.models.generate_share_token, editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('report_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='reports.reportversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to='reports.securesharelink')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
