# Generated by Django 5.0.14 on 2026-07-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportversion',
            name='report_type',
            field=models.CharField(choices=[('shipment_dossier', 'Expediente completo de embarque'), ('matching_matrix', 'Matriz de coincidencias'), ('discrepancy_report', 'Reporte de discrepancias'), ('expected_receiving_packet', 'Paquete esperado de recepción'), ('actual_receiving_report', 'Reporte real de recepción'), ('container_closure_act', 'Acta de cierre de contenedor'), ('landed_cost_report', 'Reporte de costo de importación'), ('inventory_movement_history', 'Historial de movimientos de inventario'), ('current_inventory', 'Inventario actual'), ('kit_completeness', 'Completitud de kits'), ('project_request_history', 'Historial de solicitudes de proyecto'), ('destination_reassignment_report', 'Reporte de reasignación de destino'), ('installation_acceptance_history', 'Historial de instalación/aceptación'), ('claim_package', 'Paquete de reclamo'), ('external_storage_comparison', 'Comparación de almacenaje externo'), ('confotur_reconciliation', 'Conciliación CONFOTUR'), ('responsibility_handoff_timeline', 'Línea de tiempo de responsabilidad'), ('full_traceability_timeline', 'Línea de tiempo de trazabilidad completa'), ('html_snapshot', 'Instantánea HTML autónoma')], max_length=50),
        ),
    ]
