# Generated by Django 5.0.14 on 2026-07-19 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_role_can_override_gates'),
        ('documents', '0002_initial'),
        ('drawings', '0001_initial'),
        ('projects', '0002_building_building_number_floor_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPlanTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='Stable slug, e.g. "palmera-a-all_floors".', max_length=80)),
                ('unit_type_letter', models.CharField(help_text='Apartment letter/type as in the source, e.g. "A", "D (PH)".', max_length=20)),
                ('floor_variant', models.CharField(choices=[('first_floor', 'Planta baja / primer nivel'), ('upper_floor', 'Niveles superiores'), ('all_floors', 'Todos los niveles (sin variante)'), ('penthouse_duplex', 'Penthouse dúplex')], max_length=30)),
                ('is_mirrored', models.BooleanField(default=False)),
                ('orientation', models.CharField(blank=True, help_text='Free-text orientation note when relevant, e.g. "esquina norte".', max_length=50)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('needs_review', 'Requiere revisión'), ('approved', 'Aprobado para uso operativo'), ('missing_source', 'Fuente faltante'), ('superseded', 'Reemplazado')], default='draft', max_length=20)),
                ('uncertainty_notes', models.TextField(blank=True, help_text='Documents why a slot is Missing Source / Needs Review, or any known ambiguity.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('derived_plan_document', models.ForeignKey(blank=True, help_text='The derived crop/image (own Document/DocumentVersion, own checksum) — never the original architect file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_plan_templates', to='projects.buildingfamily')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_plan_templates', to='accounts.organization')),
                ('source_drawing', models.ForeignKey(blank=True, help_text='Immutable source drawing this template was derived from — never modified by this app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_plan_templates', to='drawings.drawing')),
                ('supersedes', models.OneToOneField(blank=True, help_text='The exact prior template revision this one replaces — never edited, only marked superseded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='unitplans.unitplantemplate')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['family__display_name', 'unit_type_letter', 'floor_variant'],
            },
        ),
        migrations.CreateModel(
            name='UnitPlanAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='unitplans.unitplanassignment')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assignments', to='projects.unit')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='unitplans.unitplantemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone_code', models.CharField(help_text='Stable code within the template, e.g. "kitchen", "bedroom-1".', max_length=50)),
                ('name_es', models.CharField(max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('zone_type', models.CharField(choices=[('entrance', 'Entrada'), ('lobby_hallway', 'Vestíbulo/pasillo'), ('living_room', 'Sala'), ('dining_room', 'Comedor'), ('kitchen', 'Cocina'), ('primary_bedroom', 'Habitación principal'), ('secondary_bedroom', 'Habitación secundaria'), ('additional_bedroom', 'Habitación adicional'), ('bathroom', 'Baño'), ('half_bathroom', 'Medio baño'), ('service_room', 'Cuarto de servicio'), ('laundry', 'Lavandería'), ('balcony', 'Balcón'), ('terrace', 'Terraza'), ('closet', 'Closet'), ('mechanical_service', 'Área mecánica/servicio'), ('hotel_room', 'Habitación de hotel'), ('common_area', 'Área común'), ('other', 'Otro (configurable)')], max_length=30)),
                ('custom_type_label', models.CharField(blank=True, help_text='Used only when zone_type="other".', max_length=100)),
                ('shape_type', models.CharField(choices=[('rect', 'Rectángulo'), ('polygon', 'Polígono')], default='rect', max_length=10)),
                ('coordinates', models.JSONField(help_text='Relative (0-1) coordinates: {x0,y0,x1,y1} for rect, or [{x,y}, ...] for polygon.')),
                ('duplex_floor', models.CharField(blank=True, help_text='Which physical level within a duplex, e.g. "4" or "5".', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('validation_state', models.CharField(choices=[('draft', 'Borrador'), ('needs_review', 'Requiere revisión'), ('validated', 'Validado')], default='draft', max_length=20)),
                ('source_confidence', models.CharField(choices=[('confirmed', 'Confirmado por persona'), ('high', 'Confianza alta (automático)'), ('medium', 'Confianza media (automático)'), ('low', 'Confianza baja (automático)'), ('unknown', 'Desconocido')], default='low', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, help_text='The exact prior zone shape this one replaces — never edited, only marked superseded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='unitplans.planzone')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='unitplans.unitplantemplate')),
            ],
            options={
                'ordering': ['template', 'display_order', 'zone_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='unitplantemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('organization', 'code'), name='unique_current_template_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='unitplanassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('unit',), name='unique_current_assignment_per_unit'),
        ),
    ]
